# Generated by Django 6.0.4 on 2026-05-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('ssn', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('current_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProofOfIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=255)),
                ('employer_address', models.CharField(max_length=255)),
                ('employer_phone', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=255)),
                ('employment_start_date', models.DateField()),
                ('employment_status', models.CharField(max_length=20)),
                ('gross_monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_frequency', models.CharField(max_length=20)),
                ('document_type', models.CharField(max_length=50)),
                ('document_file', models.FileField(upload_to='proof_of_income/')),
                ('verified', models.BooleanField(default=False)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect.prospect')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoID',
            fields=[
                ('id_type', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('issuing_authority', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('name_on_id', models.CharField(max_length=255)),
                ('address_on_id', models.CharField(max_length=255)),
                ('date_of_birth_on_id', models.DateField()),
                ('document_file', models.FileField(upload_to='photo_ids/')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect.prospect')),
            ],
        ),
        migrations.CreateModel(
            name='CreditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('credit_score', models.IntegerField()),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_debt_payments', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repayment_history_status', models.CharField(max_length=20)),
                ('has_eviction_history', models.BooleanField()),
                ('eviction_count', models.IntegerField(default=0)),
                ('has_criminal_record', models.BooleanField()),
                ('criminal_record_details', models.TextField(blank=True, null=True)),
                ('pending_payments_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bankruptcy_history', models.BooleanField()),
                ('report_file', models.FileField(upload_to='credit_reports/')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect.prospect')),
            ],
        ),
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('current_address', models.CharField(max_length=255)),
                ('previous_address', models.CharField(blank=True, max_length=255, null=True)),
                ('move_in_date_requested', models.DateField()),
                ('current_landlord_name', models.CharField(max_length=255)),
                ('current_landlord_contact', models.CharField(max_length=20)),
                ('reason_for_moving', models.TextField()),
                ('number_of_occupants', models.IntegerField()),
                ('pets', models.BooleanField()),
                ('pet_details', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('references', models.JSONField(blank=True, null=True)),
                ('document_file', models.FileField(upload_to='rental_applications/')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect.prospect')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_mismatch', models.BooleanField()),
                ('address_mismatch_details', models.TextField(blank=True, null=True)),
                ('name_mismatch', models.BooleanField()),
                ('name_mismatch_details', models.TextField(blank=True, null=True)),
                ('debt_to_income_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dti_flag', models.BooleanField()),
                ('repayment_history_flag', models.BooleanField()),
                ('ability_to_pay_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall_risk_level', models.CharField(max_length=20)),
                ('recommendation', models.CharField(max_length=20)),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('screened_by', models.CharField(max_length=255)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect.prospect')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('source_document', models.CharField(max_length=255)),
                ('screening_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect.screeningresult')),
            ],
        ),
        migrations.CreateModel(
            name='UnitQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('property_name', models.CharField(max_length=255)),
                ('property_address', models.CharField(max_length=255)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lease_term_months', models.IntegerField()),
                ('lease_start_date', models.DateField()),
                ('lease_end_date', models.DateField()),
                ('additional_fees', models.JSONField(blank=True, null=True)),
                ('quote_date', models.DateField(auto_now_add=True)),
                ('quote_expiration', models.DateField()),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospect.prospect')),
            ],
        ),
    ]
